{{- if .Values.serviceaccount }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1

metadata:
  name: {{ .Release.Namespace }}-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "freshdesk-mcp.labels" . | nindent 4 }}

rules:
  {{- toYaml .Values.serviceaccount.rules | nindent 2 }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.serviceaccount.workloadidentity.enabled }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.serviceaccount.workloadidentity.clientid }}
    azure.workload.identity/tenant-id: {{ .Values.serviceaccount.workloadidentity.tenantid }}
  {{- end }}
  labels:
    {{- include "freshdesk-mcp.labels" . | nindent 4 }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Namespace }}-binding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "freshdesk-mcp.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Namespace }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Release.Namespace }}-role
  apiGroup: rbac.authorization.k8s.io
---
{{- $Values := .Values -}}
{{- $Release := .Release -}}
{{- $Root := . -}}
{{- range $index, $namespace := .Values.serviceaccount.namespaces }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1

metadata:
  name: {{ $Release.Namespace }}-role-{{ $namespace }}
  namespace: {{ $namespace }}
  labels:
    {{- include "freshdesk-mcp.labels" $Root | nindent 4 }}

rules:
  {{- toYaml $Values.serviceaccount.rules | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $Release.Namespace }}-binding-{{ $namespace }}
  namespace: {{ $namespace }}
  labels:
    {{- include "freshdesk-mcp.labels" $Root | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ $Release.Namespace }}
    namespace: {{ $Release.Namespace }}
roleRef:
  kind: Role
  name: {{ $Release.Namespace }}-role-{{ $namespace }}
  apiGroup: rbac.authorization.k8s.io
---
{{- end }}
{{- end }}